'use client';
import React from 'react';
import { AppBar } from '@/components/AppBar';
import { Button } from '@/components/Button';
import { TextField } from '@/components/TextField';
import { createClient } from '@/lib/supabase/client';

declare global { interface Window { Razorpay?: new (options:any)=>{open:()=>void} } }
export default function BusinessFunds(){
  const [amount,setAmount]=React.useState('50'),[balance,setBalance]=React.useState<{paid_days:number;test_days:number;trial_ends_at:string}|null>(null),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState('');
  React.useEffect(()=>{void (async()=>{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user)return;const {data}=await db.from('queues').select('id,paid_days,test_days,trial_ends_at').eq('owner_id',user.id).is('deleted_at',null).order('created_at',{ascending:true}).limit(1).maybeSingle();if(data){const {data:ent}=await db.rpc('refresh_queue_entitlement',{p_queue_id:data.id});setBalance({paid_days:ent?.paid_days??data.paid_days,test_days:ent?.test_days??data.test_days,trial_ends_at:ent?.trial_ends_at??data.trial_ends_at})}})()},[]);
  const pay=async()=>{const n=Number(amount);if(!Number.isInteger(n)||n<10||n>500){setMessage('₹10 se ₹500 ke beech amount chunein.');return}setBusy(true);setMessage('');try{const orderRes=await fetch('/api/payments/create-order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:n})});const order=await orderRes.json();if(!orderRes.ok)throw new Error(order.error==='payments_not_configured'?'Payment gateway abhi configure nahi hai.':order.error||'Order nahi ban paya.');if(!window.Razorpay){await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Payment window load nahi hui.'));document.body.appendChild(s)})}const checkout=new window.Razorpay!({key:order.keyId,amount:order.amount,currency:order.currency,name:'Token App',description:`${n} queue days`,order_id:order.orderId,handler:async(response:any)=>{const verify=await fetch('/api/payments/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(response)});const result=await verify.json();setMessage(verify.ok?'Payment verify ho gaya. Days add kar diye.':'Payment verify nahi ho saka. Support se sampark karein.');if(verify.ok)window.location.reload()},modal:{ondismiss:()=>setMessage('Payment poora nahi hua; balance nahi badla.')}});checkout.open()}catch(e){setMessage(e instanceof Error?e.message:'Payment shuru nahi ho paya.')}finally{setBusy(false)}};
  return <><AppBar title="Add business days" onBack={()=>history.back()}/><main className="container page tight"><section className="card"><h2 className="t-h2">Business balance</h2><p className="t-body">Paid: {balance?.paid_days??'—'} din · Test: {balance?.test_days??'—'} din</p>{balance&&<p className="t-caption">Free trial khatam: {new Date(balance.trial_ends_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</p>}</section><p className="t-body">₹1 = 1 din. Amount ₹10–₹500. Gateway payment verify hone ke baad hi din add honge.</p><TextField label="Rupees" type="number" inputMode="numeric" min={10} max={500} value={amount} onChange={e=>setAmount(e.target.value)}/><Button fullWidth loading={busy} onClick={pay}>Secure payment karein</Button>{message&&<p role="status" className="t-body-sm">{message}</p>}<p className="t-caption">Razorpay secure checkout · Payment cancel hone par balance nahi badhega.</p></main></>;
}
