'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, CircleHelp, Clock3, MoreVertical, Pause, Play, QrCode, Settings, Trash2, UserPlus, Volume2, Moon, Users } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Banner } from '@/components/Banner';
import { BottomSheet } from '@/components/BottomSheet';
import { Button } from '@/components/Button';
import { CoachTip } from '@/components/CoachTip';
import { Card, PersonRow } from '@/components/Cards';
import { Chip } from '@/components/Chip';
import { Dialog } from '@/components/Dialog';
import { EmptyState } from '@/components/EmptyState';
import { IconButton } from '@/components/IconButton';
import { NumberFlip } from '@/components/NumberFlip';
import { Skeleton } from '@/components/Skeleton';
import { StickyBar } from '@/components/StickyBar';
import { TextField } from '@/components/TextField';
import { Toast, type ToastType } from '@/components/Toast';
import { ToggleRow } from '@/components/Toggle';
import { createClient } from '@/lib/supabase/client';
import { useOnline } from '@/lib/useOnline';
import { QRCodeSVG } from '@/components/QRCodeSVG';

export type ConsoleToken = { id: string; number: number; display_name: string; is_walkin: boolean; status: string; hidden_for_owner: boolean; created_at: string; called_at: string | null };
export type ConsoleData = { queue: { id: string; name: string; code: string; status: 'live'|'paused'|'closed'; start_number: number; token_limit: number|null }; session: { id: string; started_at: string; current_number: number|null; version: number } | null; tokens: ConsoleToken[] };

type ToastState = { message: string; type: ToastType; undo?: boolean } | null;
type NumberMove = { from: number | null; to: number; direction: 'ahead' | 'back' };

function digitFont(n: number | null) { const len = String(n ?? '—').length; return len <= 3 ? 'clamp(88px,30vw,120px)' : len === 4 ? 'clamp(64px,22vw,88px)' : 'clamp(48px,16vw,64px)'; }
function fmtTime(v: string) { return new Intl.DateTimeFormat('en-IN', { hour:'numeric', minute:'2-digit', hour12:true, timeZone:'Asia/Kolkata' }).format(new Date(v)); }

export default function OwnerConsole({ initial }: { initial: ConsoleData }) {
  const router = useRouter(); const online = useOnline();
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(false); const [sheet, setSheet] = useState<'more'|'walkin'|'restart'|'skip-menu'|null>(null); const [recoveryRestart,setRecoveryRestart]=useState(false); const [dialog, setDialog] = useState<ConsoleToken|null>(null); const [skipTarget,setSkipTarget]=useState<ConsoleToken|null>(null); const [skipConfirm,setSkipConfirm]=useState(false); const [lifeDialog, setLifeDialog] = useState<'end'|'delete'|'permanent'|null>(null); const [toast, setToast] = useState<ToastState>(null); const [lastMove, setLastMove] = useState<NumberMove | null>(null); const [walkName, setWalkName] = useState(''); const [restartNumber,setRestartNumber]=useState('1'); const [restartError,setRestartError]=useState(''); const [sound, setSound] = useState(false); const [menuBusy, setMenuBusy] = useState(false); const [origin,setOrigin]=useState(''); const [scrollTop,setScrollTop]=useState(0); const [rowHeight,setRowHeight]=useState(0);
  const listRef = useRef<HTMLDivElement>(null); const lockRef = useRef(false); const undoRef = useRef<{queueId:string}|null>(null); const wakeRef = useRef<any>(null);
  useEffect(()=>setOrigin(window.location.origin),[]);
  useEffect(()=>{const root=getComputedStyle(document.documentElement);setRowHeight(Number.parseFloat(root.getPropertyValue('--owner-row-height'))*Number.parseFloat(root.fontSize))},[]);

  const load = useCallback(async () => {
    const sb = createClient();
    const [{ data:q }, { data:s }] = await Promise.all([
      sb.from('queues').select('id,name,code,status,start_number,token_limit').eq('id',initial.queue.id).is('deleted_at',null).maybeSingle(),
      sb.from('sessions').select('id,started_at,current_number,version').eq('queue_id',initial.queue.id).is('ended_at',null).order('started_at',{ascending:false}).limit(1).maybeSingle(),
    ]);
    if (q) { const {data:tokens}=s?await sb.from('tokens').select('id,number,display_name,is_walkin,status,hidden_for_owner,created_at,called_at').eq('session_id',s.id).eq('hidden_for_owner',false).order('number',{ascending:true}):{data:[]}; setData({ queue:q as ConsoleData['queue'], session:s as ConsoleData['session'], tokens:(tokens||[]) as ConsoleToken[] }); }
  }, [initial.queue.id, initial.session?.id]);

  useEffect(() => { if (!online) return; const id = window.setInterval(() => void load(), 5000); return () => window.clearInterval(id); }, [online, load]);
  useEffect(() => { const sb=createClient(); const ch=sb.channel(`queue-${data.queue.id}`).on('postgres_changes',{event:'*',schema:'public',table:'tokens',filter:`session_id=eq.${data.session?.id||'none'}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'sessions',filter:`queue_id=eq.${data.queue.id}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'queues',filter:`id=eq.${data.queue.id}`},()=>void load()).subscribe(); return ()=>{ void sb.removeChannel(ch); }; }, [data.queue.id,data.session?.id,load]);
  useEffect(() => { const fn=()=>void load(); document.addEventListener('visibilitychange',fn); return ()=>document.removeEventListener('visibilitychange',fn); },[load]);
  useEffect(()=>{if(new URLSearchParams(window.location.search).get('recovered')==='1'){setToast({message:'Queue wapas aa gayi.',type:'success'});setRecoveryRestart(true);setSheet('restart');window.history.replaceState(null,'',window.location.pathname)}},[]);
  useEffect(() => { const nav=navigator as Navigator & { wakeLock?: any }; if (!nav.wakeLock) return; let active=true; const acquire=async()=>{ try { if(active) wakeRef.current=await nav.wakeLock.request('screen'); } catch {} }; void acquire(); return ()=>{ active=false; void wakeRef.current?.release?.(); }; }, []);

  const current = data.tokens.find(t=>t.status==='serving') || null; const visibleNumber = current?.number ?? data.session?.current_number ?? data.queue.start_number; const waiting = data.tokens.filter(t=>t.status==='waiting'); const list = data.tokens; const currentTokens=useRef(list); currentTokens.current=list;
  const focusCurrent = useCallback((smooth=false) => { const box=listRef.current; if(!box) return; const rows=currentTokens.current; const currentIndex=rows.findIndex(t=>t.status==='serving'); const idx=Math.max(0,currentIndex>=0?currentIndex:rows.findIndex(t=>t.status==='waiting')); if(rows.length>30&&rowHeight){box.scrollTo({top:Math.max(0,idx*rowHeight-rowHeight*2),behavior:smooth?'smooth':'auto'});return;} const target=box.querySelector<HTMLElement>('[data-current-row="true"]') || box.querySelector<HTMLElement>('[data-first-row="true"]'); if(target)box.scrollTo({top:Math.max(0,target.offsetTop-target.offsetHeight*2),behavior:smooth?'smooth':'auto'}); },[rowHeight]);
  useEffect(()=>{ const id=window.setTimeout(()=>focusCurrent(false),0); return()=>window.clearTimeout(id); },[data.session?.id,rowHeight]);

  const act = useCallback(async (fn:string,args:unknown[], opts?:{focus?:boolean}) => { if(lockRef.current) return; if(!online){setToast({message:'Offline. Dobara connect hone par koshish karein.',type:'error'});return;} lockRef.current=true; setLoading(true); try { const {data:r,error}=await createClient().rpc(fn,Object.fromEntries(args as any)); if(error || !r){setToast({message:'Number badal nahi paya. Dobara koshish karein.',type:'error'});return;} if(r.result==='empty'){setToast({message:'Ab line me koi nahi hai.',type:'info'});return;} if(r.result==='no_prev'){setToast({message:'Pichla number nahi hai.',type:'info'});return;} if(r.result==='stale'){setToast({message:'Undo ab available nahi hai.',type:'info'});return;} if(r.result!=='ok'){setToast({message:'Number badal nahi paya. Dobara koshish karein.',type:'error'});return;} await load(); if(opts?.focus) window.setTimeout(()=>focusCurrent(true),50); return r; } finally { setLoading(false); window.setTimeout(()=>{lockRef.current=false;},300); } },[online,load,focusCurrent]);

  const next = async()=>{ const before=data; const cur=data.tokens.find(token=>token.status==='serving'); const nxt=data.tokens.find(token=>token.status==='waiting'); if(nxt){setData(value=>({...value,session:value.session?{...value.session,current_number:nxt.number,version:value.session.version+1}:null,tokens:value.tokens.map(token=>token.id===nxt.id?{...token,status:'serving'}:token.id===cur?.id?{...token,status:'done'}:token)}));} const r=await act('owner_next',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok'){navigator.vibrate?.(12); if(sound) speak(`Token number ${r.number}`);pushEvent('next');undoRef.current={queueId:data.queue.id}; setLastMove({from:cur?.number??null,to:Number(r.number),direction:'ahead'});setToast({message:`Number ${r.number} par gaye`,type:'info',undo:true});}else setData(before); };
  const skip = async()=>{if(!skipTarget)return;const target=skipTarget;const from=current?.number??null;setSkipTarget(null);setSkipConfirm(false);setSheet(null);const r=await act('owner_skip',[['p_queue_id',data.queue.id],['p_token_id',target.id]],{focus:true});if(r?.result==='ok'){pushEvent('next');undoRef.current={queueId:data.queue.id};setLastMove({from,to:Number(r.number),direction:'ahead'});setToast({message:`#${target.number} nikal gaya`,type:'info',undo:true})}};
  const prev = async()=>{ const from=current?.number??null;const r=await act('owner_prev',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok'){navigator.vibrate?.(12);setLastMove({from,to:Number(r.number),direction:'back'});setToast({message:`Number ${r.number} par gaye`,type:'info',undo:true});} };
  const undo = async()=>{ const r=await act('owner_undo',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok') setToast({message:'Undo ho gaya.',type:'success'}); };
  const speak=(text:string)=>{ if(typeof window!=='undefined' && 'speechSynthesis' in window){ window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(text)); } };
  const pushEvent=(event:'next'|'paused'|'closed'|'removed',tokenId?:string)=>{void fetch('/api/push/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({queueId:data.queue.id,event,tokenId})}).then(async response=>{if(response.ok)return;const body=await response.json().catch(()=>({}));const message=body.error==='push_not_configured'?'Push setup poora nahi hai. VAPID_PRIVATE_KEY aur VAPID_SUBJECT set karein.':'Push notification nahi bheji ja saki. Server settings check karein.';setToast(current=>current?{...current,message,type:'error'}:{message,type:'error'});}).catch(()=>setToast(current=>current?{...current,message:'Push server se connect nahi ho paya.',type:'error'}:{message:'Push server se connect nahi ho paya.',type:'error'}))};
  const addWalkin=async()=>{ const name=walkName.trim(); if(!name){setToast({message:'Naam likhein.',type:'error'});return;} const {data:r,error}=await createClient().rpc('owner_walkin',{p_queue_id:data.queue.id,p_name:name}); if(error||!r||r.result!=='ok'){setToast({message:r?.result==='limit'?'Token limit poori ho gayi.':'Walk-in nahi jud paya. Dobara koshish karein.',type:'error'});return;} setSheet(null);setWalkName('');await load();setToast({message:`${name} ko number ${r.number} mila`,type:'success'}); };
  const remove=async()=>{ if(!dialog)return; const t=dialog; setDialog(null); const {data:r,error}=await createClient().rpc('owner_remove',{p_queue_id:data.queue.id,p_token_id:t.id}); if(error||!r||r.result!=='ok'){setToast({message:'Hata nahi paye. Dobara koshish karein.',type:'error'});return;}pushEvent('removed',t.id);await load(); setToast({message:`#${t.number} hata diya`,type:'info',undo:true}); };
  const togglePause=async()=>{ const nextStatus=data.queue.status==='paused'?'live':'paused'; setMenuBusy(true); const {data:r,error}=await createClient().rpc('owner_set_status',{p_queue_id:data.queue.id,p_status:nextStatus}); setMenuBusy(false); if(error||r?.result!=='ok'){setToast({message:'Line ka status nahi badal paya.',type:'error'});return;} if(nextStatus==='paused')pushEvent('paused');setSheet(null);await load();if(nextStatus==='live')setToast({message:'Line chalu ho gayi.',type:'success'}); };
  const endDay=async()=>{ setMenuBusy(true); const {data:r,error}=await createClient().rpc('owner_end_day',{p_queue_id:data.queue.id});setMenuBusy(false);setLifeDialog(null);if(error||r?.result!=='ok'){setToast({message:'Din khatam nahi ho paya.',type:'error'});return;}pushEvent('closed');setSheet(null);await load();setToast({message:'Din khatam. Dobara shuru karne ke liye Business tab me jayein.',type:'success'}); };
  const restart=async()=>{const n=Number(restartNumber);if(!Number.isInteger(n)||n<1||n>9999){setRestartError('Number 1 se 9999 ke beech likhein.');return;}setMenuBusy(true);const {data:r,error}=await createClient().rpc('owner_restart',{p_queue_id:data.queue.id,p_start_number:n});setMenuBusy(false);if(error||r?.result!=='ok'){setRestartError('Line dobara shuru nahi ho payi.');return;}setSheet(null);setRestartError('');setRestartNumber('1');await load();setToast({message:`Nayi shuruaat. Number ${n} se chalu.`,type:'success'}); };
  const deleteQueue=async(permanent=false)=>{setMenuBusy(true);const {data:r,error}=await createClient().rpc('owner_delete_queue',{p_queue_id:data.queue.id,p_permanent:permanent});setMenuBusy(false);setLifeDialog(null);if(error||r?.result!=='ok'){setToast({message:'Queue delete nahi ho payi.',type:'error'});return;}setToast({message:permanent?'Queue hamesha ke liye hata di.':'Queue delete ho gayi',type:'success'});if(!permanent)window.setTimeout(()=>router.replace('/app/business'),500);else router.replace('/app/business');};

  const avgWait=useMemo(()=>{ const done=list.filter(t=>t.status==='done'&&t.called_at); if(done.length<3)return 3; const vals=done.slice(-10).map(t=>Math.max(1,Math.round((new Date(t.called_at!).getTime()-new Date(t.created_at).getTime())/60000))).sort((a,b)=>a-b); const trim=vals.length>4?vals.slice(1,-1):vals; return Math.max(1,Math.round(trim.reduce((a,b)=>a+b,0)/trim.length)); },[list]);
  const statsCount=list.length; const isClosed=data.queue.status==='closed';
  const virtual=list.length>30&&rowHeight>0; const virtualStart=virtual?Math.max(0,Math.floor(scrollTop/rowHeight)-2):0; const visibleTokens=virtual?list.slice(virtualStart,virtualStart+10):list;

  return <>
    {!online && <Banner variant="offline" minutesAgo={2} testId="con.offline"/>}
    {online && data.queue.status==='paused' && <Banner variant="paused" testId="con.paused"/>}
    <main className="owner-console" data-testid="console">
      <CoachTip id="owner-console" message="Yahan se number aage badhao." />
      <header className="owner-appbar" data-testid="con.appbar"><IconButton icon={<ArrowLeft size={22}/>} aria-label="Wapas" onClick={()=>router.push('/app/business')} testId="con.back"/><h1 className="t-h3 owner-title">{data.queue.name}</h1><div className="owner-actions"><Chip variant={data.queue.status==='live'?'live':data.queue.status==='paused'?'paused':'closed'} label={data.queue.status==='live'?'Live':data.queue.status==='paused'?'Paused':'Closed'}/><IconButton icon={<MoreVertical size={22}/>} aria-label="More" onClick={()=>setSheet('more')} testId="con.more"/></div></header>
      <div className="owner-grid">
        <section className="owner-main">
          <Card className="owner-ticket" style={{backgroundColor:'var(--c-accent)',borderColor:'transparent',color:'var(--c-on-accent)'}} testId="con.hero"><div className="t-overline owner-ticket-label">{current?'ABHI CHAL RAHA HAI':data.session?.current_number==null?'SHURUATI TOKEN NUMBER':'LAST CALLED NUMBER'}</div><div className={`owner-hero-number ${isClosed?'owner-closed':''}`}><NumberFlip value={visibleNumber} style={{fontSize:digitFont(typeof visibleNumber==='number'?visibleNumber:null),lineHeight:1,fontWeight:800}} testId="con.hero.number"/></div><div className="owner-current-name">{isClosed?'Line band hai':current ? <>{current.display_name}{current.is_walkin?' (Walk-in)':''}</>:'Abhi kisi ko nahi bulaya'}</div><div className="owner-ticket-move" aria-live="polite">{lastMove ? lastMove.from===null?`Pehla token #${lastMove.to} bulaya`: `#${lastMove.from} se #${lastMove.to} · ${Math.abs(lastMove.to-lastMove.from)} number ${lastMove.direction==='ahead'?'aage':'peeche'}` : current ? `${waiting.length} number abhi intezar me` : `Agla token ${visibleNumber} se shuru hoga`}</div><div className="t-caption owner-ticket-caption">{data.session?`Shuru: ${fmtTime(data.session.started_at)} · Aaj ${statsCount} token`:' '}</div></Card>
          <Card testId="con.qr"><p className="t-overline c2">SCAN KARKE TOKEN LEIN</p><div className="console-qr-code">{origin&&<QRCodeSVG value={`${origin}/q/${data.queue.code}`} size="100%" label={`Queue QR: ${data.queue.name}`}/>}</div><p className="t-label" style={{textAlign:'center'}}>{data.queue.name}</p><Button variant="tertiary" fullWidth href={`/app/business/${data.queue.id}/qr`}>QR dikhao / print</Button></Card>
          {!isClosed && <Button variant="secondary" fullWidth icon={<UserPlus size={20}/>} onClick={()=>setSheet('walkin')} testId="con.walkin">Walk-in add karein</Button>}
          <div className="owner-stats t-caption" data-testid="con.stats">Aaj: {statsCount} token · Ausat wait {avgWait} min</div>
          <div className="owner-list-head"><h2 className="t-h3">Intezar me ({waiting.length})</h2><Button variant="tertiary" size="sm" onClick={()=>focusCurrent(true)} testId="con.jump">Abhi ke number par</Button></div>
          <div className="owner-list-box" ref={listRef} onScroll={event=>{if(virtual)setScrollTop(event.currentTarget.scrollTop)}} data-testid="con.list">
            {list.length===0 ? <EmptyState icon={<Users/>} title="Abhi koi intezar me nahi" body="Customer QR scan karke judenge." testId="con.empty"/> : <>{virtual&&<div aria-hidden="true" style={{height:`${virtualStart*rowHeight}px`}}/>}{visibleTokens.map((token,visibleIndex)=>{ const i=virtualStart+visibleIndex;const active=token.status==='serving'; const grey=['done','left','expired','skipped'].includes(token.status); const chip=token.status==='waiting'?(token.is_walkin?'Walk-in':''):token.status==='done'?'Poora hua':token.status==='left'?'Line chhod di':token.status==='expired'?'Khatam':token.status==='removed'?'Hata diya':token.status==='skipped'?'Nikal gaya':active?'Ab chal raha':''; return <div key={token.id} data-current-row={active?'true':undefined} data-first-row={i===0?'true':undefined} className={`owner-person-row ${grey?'is-grey':''}`}><PersonRow number={token.number} name={`${token.display_name} #${token.number}`} metaText={token.status==='waiting'?`Kitne der se: ${Math.max(0,Math.floor((Date.now()-new Date(token.created_at).getTime())/60000))} min`:undefined} isNow={active} chipVariant={active?'now':token.status==='done'||token.status==='skipped'?'left':token.status==='left'?'left':token.is_walkin?'walkin':undefined} chipLabel={chip} testId={`con.row.${token.number}`}/>{active&&<IconButton icon={<MoreVertical size={18}/>} aria-label={`Number ${token.number} options`} onClick={()=>{setSkipTarget(token);setSheet('skip-menu')}} testId={`con.row.${token.number}.menu`}/>}{(token.status==='waiting'||token.status==='left')&&<IconButton icon={<Trash2 size={18}/>} aria-label="Hatao" onClick={()=>setDialog(token)} testId={`con.row.${token.number}.remove`}/>}</div> })}{virtual&&<div aria-hidden="true" style={{height:`${Math.max(0,list.length-virtualStart-visibleTokens.length)*rowHeight}px`}}/>}</>}
          </div>
          <Card testId="con.sound"><ToggleRow icon={<Volume2 size={24}/>} label="Awaaz announcement" helperText="Awaaz tabhi aayegi jab ye screen chalu ho. Phone off ya lock karne par awaaz nahi aayegi." checked={sound} onChange={v=>{setSound(v);if(v)speak('Awaaz chalu ho gayi')}}/></Card>
        </section>
      </div>
    </main>
    {!isClosed && <StickyBar testId="con.bar"><div className="console-bar"><Button variant="secondary" size="md" onClick={prev} disabled={loading||!online||!data.session} icon={<ChevronLeft size={20}/>} testId="con.prev">Pichla</Button><Button size="md" fullWidth onClick={next} disabled={loading||!online||!data.session} testId="con.next"><span className="console-next-label">Agla <ChevronRight size={20}/></span></Button></div></StickyBar>}
    {isClosed && <div className="owner-closed-bar"><Button fullWidth onClick={()=>{setRestartNumber('1');setRestartError('');setSheet('restart')}} testId="con.restart">Dobara shuru karein</Button></div>}
    <BottomSheet isOpen={sheet==='walkin'} onClose={()=>setSheet(null)} title="Walk-in add karein" subtitle="Jinke paas phone nahi hai unka naam likhein." primaryAction={<Button fullWidth onClick={addWalkin} testId="walkin.cta">Number dein</Button>} secondaryAction={<Button fullWidth variant="tertiary" onClick={()=>setSheet(null)}>Wapas</Button>} testId="walkin.sheet"><TextField label="Naam" value={walkName} onChange={e=>setWalkName(e.target.value.slice(0,40))} autoFocus autoCapitalize="words" maxLength={40} testId="walkin.name"/></BottomSheet>
    <BottomSheet isOpen={sheet==='restart'} onClose={()=>{setSheet(null);setRecoveryRestart(false)}} title={recoveryRestart?'Isi settings se dobara shuru karein?':'Dobara shuru karein'} subtitle="Token kis number se shuru ho? Jaise 1, 10 ya 145." primaryAction={<Button fullWidth loading={menuBusy} onClick={restart} testId="restart.cta">Shuru karein</Button>} secondaryAction={<Button fullWidth variant={recoveryRestart?'secondary':'tertiary'} onClick={()=>{if(recoveryRestart)router.push(`/app/business/${data.queue.id}/settings`);else setSheet(null)}}>{recoveryRestart?'Settings badlein':'Wapas'}</Button>} testId="restart.sheet"><TextField label="Shuruaati number" type="number" inputMode="numeric" min={1} max={9999} value={restartNumber} onChange={e=>setRestartNumber(e.target.value)} helperText={`Pichhli baar: ${data.queue.start_number} se shuru hua tha. Purani history safe rehti hai.`} error={restartError||undefined} testId="restart.number"/></BottomSheet>
    <BottomSheet isOpen={sheet==='more'} onClose={()=>setSheet(null)} title="Queue options" testId="con.more.sheet"><div className="console-menu"><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/qr`)}><QrCode size={20}/>QR dikhao / print</button><button type="button" disabled={menuBusy} onClick={()=>void togglePause()}>{data.queue.status==='paused'?<Play size={20}/>:<Pause size={20}/>} {data.queue.status==='paused'?'Line chalu karein':'Line rok dein'}</button><button type="button" onClick={()=>setLifeDialog('end')}><Moon size={20}/>Din khatam (End day)</button><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/history`)}><Clock3 size={20}/>History</button><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/settings`)}><Settings size={20}/>Settings</button><button type="button" onClick={()=>setLifeDialog('delete')} style={{color:'var(--c-danger)'}}><Trash2 size={20}/>Delete karein</button><button type="button" onClick={()=>router.push('/app/guide')}><CircleHelp size={20}/>Guide (Madad)</button></div></BottomSheet>
    <BottomSheet isOpen={sheet==='skip-menu'} onClose={()=>setSheet(null)} title={`Number ${skipTarget?.number??''}`} testId="con.skip.menu"><div className="console-menu"><button type="button" onClick={()=>{setSheet(null);setSkipConfirm(true)}}>Number nikal gaya (Skip)</button></div><Button fullWidth variant="secondary" onClick={()=>{setSkipTarget(null);setSheet(null)}}>Wapas</Button></BottomSheet>
    <Dialog isOpen={lifeDialog==='end'} title="Aaj ka kaam khatam karein?" body="Bache hue token khatam ho jayenge. Customer scan karenge toh 'Ye line band hai' dikhega." primaryLabel={menuBusy?'Rukiye…':'Din khatam karein'} onPrimary={endDay} onCancel={()=>setLifeDialog(null)} testId="con.endday.confirm"/>
    <Dialog isOpen={lifeDialog==='delete'} title="Ye queue delete karein?" body={<div><p>Queue 3 din tak uske QR code ko scan karke wapas la sakte hain. Uske baad ye hamesha ke liye hat jayegi.</p><Button variant="danger-text" size="sm" onClick={()=>setLifeDialog('permanent')}>Abhi hamesha ke liye hatao</Button></div>} primaryLabel="Delete karein" primaryVariant="danger-filled" onPrimary={()=>deleteQueue(false)} onCancel={()=>setLifeDialog(null)} testId="con.delete.confirm"/>
    <Dialog isOpen={lifeDialog==='permanent'} title="Hamesha ke liye hatao?" body="Ye wapas nahi aayega." primaryLabel="Haan, hatao" primaryVariant="danger-filled" onPrimary={()=>deleteQueue(true)} onCancel={()=>setLifeDialog(null)} testId="con.delete.permanent.confirm"/>
    <Dialog isOpen={!!dialog} title="Pakka list se hatana hai?" body={dialog?.status==='left'?`#${dialog.number} ${dialog.display_name} ka naam list se hat jayega. 5 second me Undo kar sakte hain.`:`#${dialog?.number} ${dialog?.display_name} ko line se hata diya jayega aur unhe "Owner ne aapko line se hata diya" dikhega. 5 second me Undo kar sakte hain.`} primaryLabel="Haan, hatao" primaryVariant="danger-filled" onPrimary={remove} onCancel={()=>setDialog(null)} testId="con.remove.confirm"/>
    <Dialog isOpen={skipConfirm} title="Number nikal gaya?" body={`Number ${skipTarget?.number??''} ko skip karke agle waiting number ko bulaya jayega.`} primaryLabel="Haan, skip karein" primaryVariant="danger-filled" onPrimary={skip} onCancel={()=>{setSkipConfirm(false);setSkipTarget(null)}} testId="con.skip.confirm"/>
    {toast && <Toast message={toast.message} type={toast.type} actionLabel={toast.undo?'Undo':undefined} onAction={toast.undo?undo:undefined} onDismiss={()=>setToast(null)} hasBottomNav={false} hasActionBar={!isClosed} durationMs={toast.undo?5000:undefined} testId="con.toast"/>}
  </>;
}



