'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, ChevronLeft, ChevronRight, CircleHelp, Clock3, MoreVertical, Pause, Play, QrCode, Settings, Trash2, UserPlus, Volume2, Moon, Users } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Banner } from '@/components/Banner';
import { BottomSheet } from '@/components/BottomSheet';
import { Button } from '@/components/Button';
import { Card, PersonRow } from '@/components/Cards';
import { Chip } from '@/components/Chip';
import { Dialog } from '@/components/Dialog';
import { EmptyState } from '@/components/EmptyState';
import { IconButton } from '@/components/IconButton';
import { NumberFlip } from '@/components/NumberFlip';
import { Skeleton } from '@/components/Skeleton';
import { StickyBar } from '@/components/StickyBar';
import { TextField } from '@/components/TextField';
import { ToggleRow } from '@/components/Toggle';
import { createClient } from '@/lib/supabase/client';
import { useOnline } from '@/lib/useOnline';
import { QRCodeSVG } from '@/components/QRCodeSVG';

export type ConsoleToken = { id: string; number: number; display_name: string; is_walkin: boolean; status: string; hidden_for_owner: boolean; created_at: string; called_at: string | null };
export type ConsoleData = { queue: { id: string; name: string; code: string; book_id:string; status: 'live'|'paused'|'closed'; start_number: number; token_limit: number|null; paid_days:number; test_days:number; trial_ends_at:string; intake_enabled:boolean; announcement_enabled:boolean; announcement_repeat_count:number; sound_box_enabled:boolean }; session: { id: string; started_at: string; current_number: number|null; version: number } | null; tokens: ConsoleToken[] };

type ToastState = { message: string; type: 'info'|'success'|'error'; undo?: boolean } | null;
type NumberMove = { from: number | null; to: number; direction: 'ahead' | 'back' };

function digitFont(n: number | null) { const len = String(n ?? '—').length; return len <= 3 ? 'clamp(88px,30vw,120px)' : len === 4 ? 'clamp(64px,22vw,88px)' : 'clamp(48px,16vw,64px)'; }
function fmtTime(v: string) { return new Intl.DateTimeFormat('en-IN', { hour:'numeric', minute:'2-digit', hour12:true, timeZone:'Asia/Kolkata' }).format(new Date(v)); }

export default function OwnerConsole({ initial }: { initial: ConsoleData }) {
  const router = useRouter(); const online = useOnline();
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(false); const [sheet, setSheet] = useState<'more'|'walkin'|'restart'|'skip-menu'|null>(null); const [dialog, setDialog] = useState<ConsoleToken|null>(null); const [skipTarget,setSkipTarget]=useState<ConsoleToken|null>(null); const [skipConfirm,setSkipConfirm]=useState(false); const [lifeDialog, setLifeDialog] = useState<'end'|null>(null); const toast:ToastState=null; const setToast:React.Dispatch<React.SetStateAction<ToastState>>=()=>{}; const [lastMove, setLastMove] = useState<NumberMove | null>(null); const [walkName, setWalkName] = useState(''); const [restartNumber,setRestartNumber]=useState('1'); const [restartError,setRestartError]=useState(''); const [sound, setSound] = useState(initial.queue.announcement_enabled); const [repeatCount,setRepeatCount]=useState(initial.queue.announcement_repeat_count); const [soundBox,setSoundBox]=useState(initial.queue.sound_box_enabled); const [menuBusy, setMenuBusy] = useState(false); const [origin,setOrigin]=useState(''); const [scrollTop,setScrollTop]=useState(0); const [rowHeight,setRowHeight]=useState(0); const [showTop,setShowTop]=useState(false);
  const listRef = useRef<HTMLDivElement>(null); const lockRef = useRef(false); const undoRef = useRef<{queueId:string}|null>(null); const mediaAudioRef=useRef<HTMLAudioElement|null>(null); const speechQueueRef=useRef<{text:string;remaining:number}|null>(null); const actionsRef=useRef<{next:()=>void;prev:()=>void}>({next:()=>{},prev:()=>{}}); const lastMediaKeyRef=useRef(0);
  useEffect(()=>setOrigin(window.location.origin),[]);
  useEffect(()=>{let timer:number|undefined;let away=false;const hero=document.querySelector('[data-testid="con.hero"]');if(!hero)return;const observer=new IntersectionObserver(entries=>{const visible=entries[0]?.isIntersecting??true;away=!visible;if(visible){window.clearTimeout(timer);setShowTop(false)}else{window.clearTimeout(timer);timer=window.setTimeout(()=>{if(away)setShowTop(true)},3000)}},{threshold:.1});observer.observe(hero);return()=>{observer.disconnect();window.clearTimeout(timer)}},[]);
  useEffect(()=>{const root=getComputedStyle(document.documentElement);setRowHeight(Number.parseFloat(root.getPropertyValue('--owner-row-height'))*Number.parseFloat(root.fontSize))},[]);

  const loadingRef=useRef(false);
  const load = useCallback(async () => {
    if(loadingRef.current || document.visibilityState==='hidden') return;
    loadingRef.current=true;
    try {
      const sb=createClient();
      const {data:q}=await sb.from('queues').select('id,name,code,status,start_number,token_limit,book_id,paid_days,test_days,trial_ends_at,intake_enabled,announcement_enabled,announcement_repeat_count,sound_box_enabled,sessions(id,started_at,current_number,version,ended_at,tokens(id,number,display_name,is_walkin,status,hidden_for_owner,created_at,called_at))').eq('id',initial.queue.id).is('deleted_at',null).order('started_at',{ascending:false,foreignTable:'sessions'}).limit(1,{foreignTable:'sessions'}).maybeSingle();
      if(q){const session=(q.sessions||[]).find((item:{ended_at?:string|null})=>!item.ended_at)||null;const {sessions:_sessions,...queue}=q as typeof q & {sessions?:Array<{id:string;started_at:string;current_number:number|null;version:number;ended_at:string|null;tokens:ConsoleToken[]}>};setData({queue:queue as ConsoleData['queue'],session:session as ConsoleData['session'],tokens:(session?.tokens||[]).filter((token:ConsoleToken)=>!token.hidden_for_owner) as ConsoleToken[]});}
    } finally { loadingRef.current=false; }
  }, [initial.queue.id]);

  useEffect(() => { if (!online) return; const id = window.setInterval(() => void load(), 15000); return () => window.clearInterval(id); }, [online, load]);
  useEffect(() => { const sb=createClient(); const ch=sb.channel(`queue-${data.queue.id}`).on('postgres_changes',{event:'*',schema:'public',table:'tokens',filter:`session_id=eq.${data.session?.id||'none'}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'sessions',filter:`queue_id=eq.${data.queue.id}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'queues',filter:`id=eq.${data.queue.id}`},()=>void load()).subscribe(); return ()=>{ void sb.removeChannel(ch); }; }, [data.queue.id,data.session?.id,load]);
  useEffect(() => { const fn=()=>{if(document.visibilityState==='visible')void load()}; document.addEventListener('visibilitychange',fn); return ()=>document.removeEventListener('visibilitychange',fn); },[load]);

  const current = data.tokens.find(t=>t.status==='serving') || null; const visibleNumber = current?.number ?? data.session?.current_number ?? data.queue.start_number; const waiting = data.tokens.filter(t=>t.status==='waiting'); const list = data.tokens; const currentTokens=useRef(list); currentTokens.current=list;
  const focusCurrent = useCallback((smooth=false) => { const box=listRef.current; if(!box) return; const rows=currentTokens.current; const currentIndex=rows.findIndex(t=>t.status==='serving'); const idx=Math.max(0,currentIndex>=0?currentIndex:rows.findIndex(t=>t.status==='waiting')); if(rows.length>30&&rowHeight){box.scrollTo({top:Math.max(0,idx*rowHeight-rowHeight*2),behavior:smooth?'smooth':'auto'});return;} const target=box.querySelector<HTMLElement>('[data-current-row="true"]') || box.querySelector<HTMLElement>('[data-first-row="true"]'); if(target)box.scrollTo({top:Math.max(0,target.offsetTop-target.offsetHeight*2),behavior:smooth?'smooth':'auto'}); },[rowHeight]);
  useEffect(()=>{ const id=window.setTimeout(()=>focusCurrent(false),0); return()=>window.clearTimeout(id); },[data.session?.id,rowHeight]);

  const act = useCallback(async (fn:string,args:unknown[], opts?:{focus?:boolean}) => { if(lockRef.current) return; if(!online){setToast({message:'Offline. Dobara connect hone par koshish karein.',type:'error'});return;} lockRef.current=true; setLoading(true); try { const {data:r,error}=await createClient().rpc(fn,Object.fromEntries(args as any)); if(error || !r){setToast({message:'Number badal nahi paya. Dobara koshish karein.',type:'error'});return;} if(r.result==='empty'){setToast({message:'Ab line me koi nahi hai.',type:'info'});return;} if(r.result==='no_prev'){setToast({message:'Pichla number nahi hai.',type:'info'});return;} if(r.result==='stale'){setToast({message:'Undo ab available nahi hai.',type:'info'});return;} if(r.result!=='ok'){setToast({message:'Number badal nahi paya. Dobara koshish karein.',type:'error'});return;} if(opts?.focus) window.setTimeout(()=>focusCurrent(true),50); return r; } finally { setLoading(false); lockRef.current=false; } },[online,load,focusCurrent]);

  const next = async()=>{ const before=data; const cur=data.tokens.find(token=>token.status==='serving'); const nxt=data.tokens.find(token=>token.status==='waiting'); if(nxt){setData(value=>({...value,session:value.session?{...value.session,current_number:nxt.number,version:value.session.version+1}:null,tokens:value.tokens.map(token=>token.id===nxt.id?{...token,status:'serving'}:token.id===cur?.id?{...token,status:'done'}:token)}));} const r=await act('owner_next',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok'){navigator.vibrate?.(12); if(sound) speakRepeated(`Token number ${r.number}`,repeatCount);pushEvent('next');undoRef.current={queueId:data.queue.id}; setLastMove({from:cur?.number??null,to:Number(r.number),direction:'ahead'});setToast({message:`Number ${r.number} par gaye`,type:'info',undo:true});}else setData(before); };
  const skip = async()=>{if(!skipTarget)return;const target=skipTarget;const from=current?.number??null;setSkipTarget(null);setSkipConfirm(false);setSheet(null);const r=await act('owner_skip',[['p_queue_id',data.queue.id],['p_token_id',target.id]],{focus:true});if(r?.result==='ok'){pushEvent('next');undoRef.current={queueId:data.queue.id};setLastMove({from,to:Number(r.number),direction:'ahead'});setToast({message:`#${target.number} nikal gaya`,type:'info',undo:true})}};
  const prev = async()=>{ const from=current?.number??null;const r=await act('owner_prev',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok'){navigator.vibrate?.(12);setLastMove({from,to:Number(r.number),direction:'back'});setToast({message:`Number ${r.number} par gaye`,type:'info',undo:true});} };
  const undo = async()=>{ const r=await act('owner_undo',[['p_queue_id',data.queue.id]],{focus:true}); if(r?.result==='ok') setToast({message:'Undo ho gaya.',type:'success'}); };
  const speakRepeated=(text:string,count:number)=>{if(!('speechSynthesis'in window))return;const synth=window.speechSynthesis;synth.cancel();speechQueueRef.current={text,remaining:Math.max(1,Math.min(4,count))};const speakNext=()=>{const queue=speechQueueRef.current;if(!queue||queue.remaining<=0){speechQueueRef.current=null;return}const utterance=new SpeechSynthesisUtterance(queue.text);utterance.onend=()=>{if(speechQueueRef.current){speechQueueRef.current.remaining-=1;speakNext()}};utterance.onerror=()=>{speechQueueRef.current=null};synth.speak(utterance)};speakNext()};
  const pushEvent=(event:'next'|'paused'|'closed'|'removed',tokenId?:string)=>{void fetch('/api/push/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({queueId:data.queue.id,event,tokenId})}).catch(()=>{});};
  const addWalkin=async()=>{ const name=walkName.trim(); if(!name){setToast({message:'Naam likhein.',type:'error'});return;} const {data:r,error}=await createClient().rpc('owner_walkin',{p_queue_id:data.queue.id,p_name:name}); if(error||!r||r.result!=='ok'){setToast({message:r?.result==='limit'?'Token limit poori ho gayi.':'Walk-in nahi jud paya. Dobara koshish karein.',type:'error'});return;} setSheet(null);setWalkName('');await load();setToast({message:`${name} ko number ${r.number} mila`,type:'success'}); };
  const remove=async()=>{ if(!dialog)return; const t=dialog; setDialog(null); const {data:r,error}=await createClient().rpc('owner_remove',{p_queue_id:data.queue.id,p_token_id:t.id}); if(error||!r||r.result!=='ok'){setToast({message:'Hata nahi paye. Dobara koshish karein.',type:'error'});return;}pushEvent('removed',t.id);await load(); setToast({message:`#${t.number} hata diya`,type:'info',undo:true}); };
  const togglePause=async()=>{ const nextStatus=data.queue.status==='paused'?'live':'paused'; setMenuBusy(true); const {data:r,error}=await createClient().rpc('owner_set_status',{p_queue_id:data.queue.id,p_status:nextStatus}); setMenuBusy(false); if(error||r?.result!=='ok'){setToast({message:'Line ka status nahi badal paya.',type:'error'});return;} if(nextStatus==='paused')pushEvent('paused');setSheet(null);await load();if(nextStatus==='live')setToast({message:'Line chalu ho gayi.',type:'success'}); };
  const toggleIntake=async()=>{setMenuBusy(true);const enabled=!data.queue.intake_enabled;const {data:r,error}=await createClient().rpc('owner_update_intake',{p_queue_id:data.queue.id,p_enabled:enabled});setMenuBusy(false);if(error||r?.result!=='ok'){setToast({message:'Online token setting save nahi hui.',type:'error'});return}await load();setToast({message:enabled?'Online token chalu.':'Online token band; walk-in chalu rahega.',type:'success'})};
  const saveAnnouncement=async(enabled=sound,repeat=repeatCount,box=soundBox)=>{setSound(enabled);setRepeatCount(repeat);setSoundBox(box);if(box)void mediaAudioRef.current?.play().catch(()=>{});else{mediaAudioRef.current?.pause();window.speechSynthesis?.cancel();speechQueueRef.current=null;}const {data:r,error}=await createClient().rpc('owner_update_announcements',{p_queue_id:data.queue.id,p_enabled:enabled,p_repeat:repeat,p_sound_box:box});if(error||r?.result!=='ok')setToast({message:'Announcement setting save nahi hui.',type:'error'})};
  actionsRef.current={next,prev};
  useEffect(()=>{if(!soundBox||!('mediaSession'in navigator))return;const session=navigator.mediaSession;try{session.metadata=new MediaMetadata({title:`Token ${visibleNumber} · ${data.queue.name}`,artist:'Token App'});session.setActionHandler('nexttrack',()=>actionsRef.current.next());session.setActionHandler('previoustrack',()=>actionsRef.current.prev());session.playbackState='playing'}catch{}return()=>{try{session.setActionHandler('nexttrack',null);session.setActionHandler('previoustrack',null)}catch{}}},[soundBox,data.queue.name,visibleNumber]);
  useEffect(()=>{if(!soundBox)return;const handleVisibility=()=>{if(document.visibilityState==='visible'){void mediaAudioRef.current?.play().catch(()=>{});window.speechSynthesis?.resume()}};const handleMediaKey=(event:KeyboardEvent)=>{if(!soundBox)return;const now=Date.now();if(now-lastMediaKeyRef.current<250)return;let direction:'next'|'prev'|null=null;if(event.key==='AudioVolumeUp'||event.code==='AudioVolumeUp'||event.keyCode===175)direction='next';if(event.key==='AudioVolumeDown'||event.code==='AudioVolumeDown'||event.keyCode===174)direction='prev';if(direction){lastMediaKeyRef.current=now;event.preventDefault();actionsRef.current[direction]()}};document.addEventListener('visibilitychange',handleVisibility);window.addEventListener('keydown',handleMediaKey);return()=>{document.removeEventListener('visibilitychange',handleVisibility);window.removeEventListener('keydown',handleMediaKey)}},[soundBox]);

  const endDay=async()=>{ setMenuBusy(true); const {data:r,error}=await createClient().rpc('owner_end_day',{p_queue_id:data.queue.id});setMenuBusy(false);setLifeDialog(null);if(error||r?.result!=='ok'){setToast({message:'Din khatam nahi ho paya.',type:'error'});return;}pushEvent('closed');setSheet(null);await load();setToast({message:'Din khatam. Dobara shuru karne ke liye Business tab me jayein.',type:'success'}); };
  const restart=async()=>{const n=Number(restartNumber);if(!Number.isInteger(n)||n<1||n>9999){setRestartError('Number 1 se 9999 ke beech likhein.');return;}setMenuBusy(true);const {data:r,error}=await createClient().rpc('owner_restart',{p_queue_id:data.queue.id,p_start_number:n});setMenuBusy(false);if(error||r?.result!=='ok'){setRestartError('Line dobara shuru nahi ho payi.');return;}setSheet(null);setRestartError('');setRestartNumber('1');await load();setToast({message:`Nayi shuruaat. Number ${n} se chalu.`,type:'success'}); };

  const avgWait=useMemo(()=>{ const done=list.filter(t=>t.status==='done'&&t.called_at); if(done.length<3)return 3; const vals=done.slice(-10).map(t=>Math.max(1,Math.round((new Date(t.called_at!).getTime()-new Date(t.created_at).getTime())/60000))).sort((a,b)=>a-b); const trim=vals.length>4?vals.slice(1,-1):vals; return Math.max(1,Math.round(trim.reduce((a,b)=>a+b,0)/trim.length)); },[list]);
  const statsCount=list.length; const isClosed=data.queue.status==='closed';
  const virtual=list.length>30&&rowHeight>0; const virtualStart=virtual?Math.max(0,Math.floor(scrollTop/rowHeight)-2):0; const visibleTokens=virtual?list.slice(virtualStart,virtualStart+10):list;

  return <>
    {!online && <Banner variant="offline" minutesAgo={2} testId="con.offline"/>}
    {online && data.queue.status==='paused' && <Banner variant="paused" testId="con.paused"/>}
    <main className="owner-console" data-testid="console"><audio ref={mediaAudioRef} src="/sounds/silence.wav" loop playsInline preload="auto" aria-hidden="true" style={{display:"none"}}/>
      
      <header className="owner-appbar" data-testid="con.appbar"><IconButton icon={<ArrowLeft size={22}/>} aria-label="Wapas" onClick={()=>router.push('/app/business')} testId="con.back"/><h1 className="t-h3 owner-title">{data.queue.name}</h1><div className="owner-actions"><Chip variant={data.queue.status==='live'?'live':data.queue.status==='paused'?'paused':'closed'} label={data.queue.status==='live'?'Live':data.queue.status==='paused'?'Paused':'Closed'}/><IconButton icon={<MoreVertical size={22}/>} aria-label="More" onClick={()=>setSheet('more')} testId="con.more"/></div></header>
      <div className="owner-grid">
        <section className="owner-main">
          <Card className="owner-ticket" style={{backgroundColor:'var(--c-accent)',borderColor:'transparent',color:'var(--c-on-accent)'}} testId="con.hero"><div className="t-overline owner-ticket-label">{current?'ABHI CHAL RAHA HAI':data.session?.current_number==null?'SHURUATI TOKEN NUMBER':'LAST CALLED NUMBER'}</div><div className={`owner-hero-number ${isClosed?'owner-closed':''}`}><NumberFlip value={visibleNumber} style={{fontSize:digitFont(typeof visibleNumber==='number'?visibleNumber:null),lineHeight:1,fontWeight:800}} testId="con.hero.number"/></div><div className="owner-current-name">{isClosed?'Line band hai':current ? <>{current.display_name}{current.is_walkin?' (Walk-in)':''}</>:'Abhi kisi ko nahi bulaya'}</div><div className="owner-ticket-move" aria-live="polite">{lastMove ? lastMove.from===null?`Pehla token #${lastMove.to} bulaya`: `#${lastMove.from} se #${lastMove.to} · ${Math.abs(lastMove.to-lastMove.from)} number ${lastMove.direction==='ahead'?'aage':'peeche'}` : current ? `${waiting.length} number abhi intezar me` : `Agla token ${visibleNumber} se shuru hoga`}</div><div className="t-caption owner-ticket-caption">{data.session?`Shuru: ${fmtTime(data.session.started_at)} · Aaj ${statsCount} token`:' '}</div></Card>
          <Card testId="con.qr"><p className="t-overline c2">SCAN KARKE TOKEN LEIN</p><div className="console-qr-code">{origin&&<QRCodeSVG value={`${origin}/q/${data.queue.code}`} size="100%" label={`Queue QR: ${data.queue.name}`}/>}</div><p className="t-label" style={{textAlign:'center'}}>{data.queue.name}</p><p className="t-body-sm" style={{textAlign:'center'}}>Book ID: <strong>{data.queue.book_id}</strong></p><p className="t-caption" style={{textAlign:'center'}}>Balance: {data.queue.paid_days+data.queue.test_days+Math.max(0,Math.ceil((Date.parse(data.queue.trial_ends_at)-Date.now())/86400000))} din · Trial {new Date(data.queue.trial_ends_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</p><Button variant="tertiary" fullWidth href={`/app/business/${data.queue.id}/qr`}>QR dikhao / print</Button><Button variant="tertiary" fullWidth href="/app/business/funds">Days add karein</Button></Card>
          {!isClosed && <Button variant="secondary" fullWidth icon={<UserPlus size={20}/>} onClick={()=>setSheet('walkin')} testId="con.walkin">Walk-in add karein</Button>}
          <div className="owner-stats t-caption" data-testid="con.stats">Aaj: {statsCount} token · Ausat wait {avgWait} min</div>
          <div className="owner-list-head"><h2 className="t-h3">Intezar me ({waiting.length})</h2><Button variant="tertiary" size="sm" onClick={()=>focusCurrent(true)} testId="con.jump">Abhi ke number par</Button></div>
          <div className="owner-list-box" ref={listRef} onScroll={event=>{if(virtual)setScrollTop(event.currentTarget.scrollTop)}} data-testid="con.list">
            {list.length===0 ? <EmptyState icon={<Users/>} title="Abhi koi intezar me nahi" body="Customer QR scan karke judenge." testId="con.empty"/> : <>{virtual&&<div aria-hidden="true" style={{height:`${virtualStart*rowHeight}px`}}/>}{visibleTokens.map((token,visibleIndex)=>{ const i=virtualStart+visibleIndex;const active=token.status==='serving'; const grey=['done','left','expired','skipped'].includes(token.status); const chip=token.status==='waiting'?(token.is_walkin?'Walk-in':''):token.status==='done'?'Poora hua':token.status==='left'?'Line chhod di':token.status==='expired'?'Khatam':token.status==='removed'?'Hata diya':token.status==='skipped'?'Nikal gaya':active?'Ab chal raha':''; return <div key={token.id} data-current-row={active?'true':undefined} data-first-row={i===0?'true':undefined} className={`owner-person-row ${grey?'is-grey':''}`}><PersonRow number={token.number} name={`${token.display_name} #${token.number}`} metaText={token.status==='waiting'?`Kitne der se: ${Math.max(0,Math.floor((Date.now()-new Date(token.created_at).getTime())/60000))} min`:undefined} isNow={active} chipVariant={active?'now':token.status==='done'||token.status==='skipped'?'left':token.status==='left'?'left':token.is_walkin?'walkin':undefined} chipLabel={chip} testId={`con.row.${token.number}`}/>{active&&<IconButton icon={<MoreVertical size={18}/>} aria-label={`Number ${token.number} options`} onClick={()=>{setSkipTarget(token);setSheet('skip-menu')}} testId={`con.row.${token.number}.menu`}/>}{(token.status==='waiting'||token.status==='left')&&<IconButton icon={<Trash2 size={18}/>} aria-label="Hatao" onClick={()=>setDialog(token)} testId={`con.row.${token.number}.remove`}/>}</div> })}{virtual&&<div aria-hidden="true" style={{height:`${Math.max(0,list.length-virtualStart-visibleTokens.length)*rowHeight}px`}}/>}</>}
          </div>
          <Card testId="con.sound"><ToggleRow icon={<Volume2 size={24}/>} label="Awaaz announcement" helperText="Customer ka number bolkar batayein." checked={sound} onChange={v=>void saveAnnouncement(v)}/><div className="owner-announcement-repeat"><span className="t-body-sm">Repeat</span>{[1,2,3,4].map(n=><button key={n} type="button" aria-pressed={repeatCount===n} onClick={()=>void saveAnnouncement(sound,n)}>{n}×</button>)}</div><ToggleRow label="Sound box / media buttons" helperText="Supported phones par lock screen ke next/previous controls bhi queue chalayenge." checked={soundBox} onChange={v=>void saveAnnouncement(sound,repeatCount,v)}/></Card>
        </section>
      </div>
    </main>
    {!isClosed && <StickyBar testId="con.bar"><div className="console-bar"><Button variant="secondary" size="md" onClick={prev} disabled={loading||!online||!data.session} icon={<ChevronLeft size={20}/>} testId="con.prev">Pichla</Button><Button size="md" fullWidth onClick={next} disabled={loading||!online||!data.session} testId="con.next"><span className="console-next-label">Agla <ChevronRight size={20}/></span></Button></div></StickyBar>}
    {isClosed && <div className="owner-closed-bar"><Button fullWidth onClick={()=>{setRestartNumber('1');setRestartError('');setSheet('restart')}} testId="con.restart">Dobara shuru karein</Button></div>}
    <BottomSheet isOpen={sheet==='walkin'} onClose={()=>setSheet(null)} title="Walk-in add karein" subtitle="Jinke paas phone nahi hai unka naam likhein." primaryAction={<Button fullWidth onClick={addWalkin} testId="walkin.cta">Number dein</Button>} secondaryAction={<Button fullWidth variant="tertiary" onClick={()=>setSheet(null)}>Wapas</Button>} testId="walkin.sheet"><TextField label="Naam" value={walkName} onChange={e=>setWalkName(e.target.value.slice(0,40))} autoFocus autoCapitalize="words" maxLength={40} testId="walkin.name"/></BottomSheet>
    <BottomSheet isOpen={sheet==='restart'} onClose={()=>setSheet(null)} title="Dobara shuru karein" subtitle="Token kis number se shuru ho? Jaise 1, 10 ya 145." primaryAction={<Button fullWidth loading={menuBusy} onClick={restart} testId="restart.cta">Shuru karein</Button>} secondaryAction={<Button fullWidth variant="tertiary" onClick={()=>setSheet(null)}>Wapas</Button>} testId="restart.sheet"><TextField label="Shuruaati number" type="number" inputMode="numeric" min={1} max={9999} value={restartNumber} onChange={e=>setRestartNumber(e.target.value)} helperText={`Pichhli baar: ${data.queue.start_number} se shuru hua tha. Purani history safe rehti hai.`} error={restartError||undefined} testId="restart.number"/></BottomSheet>
    <BottomSheet isOpen={sheet==='more'} onClose={()=>setSheet(null)} title="Queue options" testId="con.more.sheet"><div className="console-menu"><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/qr`)}><QrCode size={20}/>QR dikhao / print</button><button type="button" disabled={menuBusy} onClick={()=>void togglePause()}>{data.queue.status==='paused'?<Play size={20}/>:<Pause size={20}/>} {data.queue.status==='paused'?'Line chalu karein':'Line rok dein'}</button><button type="button" disabled={menuBusy} onClick={()=>void toggleIntake()}>{data.queue.intake_enabled?'Online token band karein':'Online token chalu karein'} · walk-in chalu</button><button type="button" onClick={()=>setLifeDialog('end')}><Moon size={20}/>Din khatam (End day)</button><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/history`)}><Clock3 size={20}/>History</button><button type="button" onClick={()=>router.push(`/app/business/${data.queue.id}/settings`)}><Settings size={20}/>Settings</button><button type="button" onClick={()=>router.push('/app/guide')}><CircleHelp size={20}/>Guide (Madad)</button></div></BottomSheet>
    <BottomSheet isOpen={sheet==='skip-menu'} onClose={()=>setSheet(null)} title={`Number ${skipTarget?.number??''}`} testId="con.skip.menu"><div className="console-menu"><button type="button" onClick={()=>{setSheet(null);setSkipConfirm(true)}}>Number nikal gaya (Skip)</button></div><Button fullWidth variant="secondary" onClick={()=>{setSkipTarget(null);setSheet(null)}}>Wapas</Button></BottomSheet>
    <Dialog isOpen={lifeDialog==='end'} title="Aaj ka kaam khatam karein?" body="Bache hue token khatam ho jayenge. Customer scan karenge toh 'Ye line band hai' dikhega." primaryLabel={menuBusy?'Rukiye…':'Din khatam karein'} onPrimary={endDay} onCancel={()=>setLifeDialog(null)} testId="con.endday.confirm"/>
    <Dialog isOpen={!!dialog} title="Pakka list se hatana hai?" body={dialog?.status==='left'?`#${dialog.number} ${dialog.display_name} ka naam list se hat jayega. 5 second me Undo kar sakte hain.`:`#${dialog?.number} ${dialog?.display_name} ko line se hata diya jayega aur unhe "Owner ne aapko line se hata diya" dikhega. 5 second me Undo kar sakte hain.`} primaryLabel="Haan, hatao" primaryVariant="danger-filled" onPrimary={remove} onCancel={()=>setDialog(null)} testId="con.remove.confirm"/>
    <Dialog isOpen={skipConfirm} title="Number nikal gaya?" body={`Number ${skipTarget?.number??''} ko skip karke agle waiting number ko bulaya jayega.`} primaryLabel="Haan, skip karein" primaryVariant="danger-filled" onPrimary={skip} onCancel={()=>{setSkipConfirm(false);setSkipTarget(null)}} testId="con.skip.confirm"/>
    {showTop&&<button className="owner-back-top" type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Upar jayein"><ArrowUp size={18}/></button>}
  </>;
}



