'use client';
import React from 'react';
import { RotateCcw, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Card } from '@/components/Cards';
import { Chip } from '@/components/Chip';
import { Countdown } from '@/components/Countdown';
import { Button } from '@/components/Button';
import { EmptyState } from '@/components/EmptyState';
import { Dialog } from '@/components/Dialog';
import { AppBar } from '@/components/AppBar';
import { createClient } from '@/lib/supabase/client';

type Item={id:string;name:string;kind:'queue'|'history';deleted_at:string;purge_at:string;queue_id?:string;started_at?:string;ended_at?:string};
export function RecentlyDeleted({standalone=false}:{standalone?:boolean}){
  const [items,setItems]=React.useState<Item[]>([]);const [ready,setReady]=React.useState(false);const [error,setError]=React.useState('');const [selected,setSelected]=React.useState<Item|null>(null);const [toast,setToast]=React.useState('');const [busy,setBusy]=React.useState(false);const router=useRouter();
  const load=React.useCallback(async()=>{setError('');const db=createClient();await db.rpc('purge_expired_items');const {data,error:err}=await db.rpc('owner_recently_deleted');if(err||!data){setError('Deleted items load nahi ho paye. Dobara koshish karein.');setReady(true);return;}setItems([...(data.queues||[]),...(data.sessions||[])].sort((a,b)=>new Date(b.deleted_at).getTime()-new Date(a.deleted_at).getTime()));setReady(true)},[]);
  React.useEffect(()=>{void load()},[load]);
  const restore=async(item:Item)=>{setBusy(true);const {data,error:err}=await createClient().rpc('owner_recover_item',{p_item_id:item.id,p_kind:item.kind});setBusy(false);if(err||data?.result!=='ok'){setToast('Item wapas nahi aa paya.');return;}setToast(item.kind==='queue'?'Queue wapas aa gayi.':'History wapas aa gayi.');window.dispatchEvent(new Event('queues-changed'));await load()};
  const permanentlyDelete=async()=>{if(!selected)return;setBusy(true);const {data,error:err}=await createClient().rpc(selected.kind==='queue'?'owner_delete_queue':'owner_delete_history',selected.kind==='queue'?{p_queue_id:selected.id,p_permanent:true}:{p_session_id:selected.id,p_permanent:true});setBusy(false);if(err||data?.result!=='ok'){setToast('Item hamesha ke liye nahi hat paya.');return;}setSelected(null);setToast('Item hamesha ke liye hata diya.');window.dispatchEvent(new Event('queues-changed'));await load()};
  if(!standalone&&ready&&items.length===0&&!error)return null;
  return <>{standalone&&<AppBar title="Recently Deleted" onBack={()=>router.back()} testId="rd.appbar"/>}{!standalone&&ready&&items.length>0&&<section className="container biz-old" data-testid="biz.recently-deleted"><h2 className="t-overline biz-old-h">RECENTLY DELETED</h2><p className="t-body-sm c2">Delete ki hui queue 3 din tak yahan rehti hai.</p>{items.filter(x=>x.kind==='queue').map(item=><Card key={item.id}><div className="row mid" style={{justifyContent:'space-between'}}><strong className="t-label">{item.name}</strong><Chip variant="waiting" label="Queue"/></div><p className="t-body-sm c2" style={{marginTop:'var(--sp-2)'}}>3 din me hamesha ke liye hat jayegi</p><div className="row mid" style={{marginTop:'var(--sp-2)'}}><Button size="sm" onClick={()=>void restore(item)}>Recover</Button><Button size="sm" variant="danger-text" onClick={()=>setSelected(item)}>Hamesha ke liye hatao</Button></div></Card>)}<Button variant="tertiary" size="sm" onClick={()=>router.push('/app/profile/recently-deleted')}>Sab deleted items dekhein</Button></section>}<main className="container page tight" data-testid="recently-deleted">
    {error&&<div role="alert" className="t-body-sm" style={{color:'var(--c-danger)'}}>{error}<Button variant="tertiary" size="sm" onClick={()=>void load()}>Dobara koshish karein</Button></div>}
    {ready&&items.length>0&&<Card testId="rd.info" style={{background:'var(--c-surface-2)',padding:'var(--sp-3)'}}><p className="t-body-sm">Delete kiye gaye items 3 din tak yahan rehte hain. Uske baad hamesha ke liye hat jate hain.</p><p className="t-caption c2" style={{marginTop:'var(--sp-2)'}}>Aakhri delete: {new Date(items[0].deleted_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</p></Card>}
    {!ready?<div className="t-body-sm c2">Load ho raha hai…</div>:items.length===0?<EmptyState icon={<Trash2/>} title="Koi deleted item nahi hai" body="" testId="rd.empty"/>:<div className="biz-list" data-testid="rd.list">{items.map(item=><Card key={`${item.kind}-${item.id}`} testId={`rd.item.${item.id}`}><div className="row mid" style={{justifyContent:'space-between'}}><strong className="t-label">{item.name}</strong><Chip variant="waiting" label={item.kind==='queue'?'Queue':'History'}/></div><p className="t-body-sm c2" style={{marginTop:'var(--sp-2)'}}>Delete hua: {new Date(item.deleted_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</p><p className="t-body-sm" style={{marginTop:'var(--sp-2)'}}>Hamesha ke liye hatega: {new Date(item.purge_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})} <span className="t-label" style={{color:'var(--c-next-strong)'}}><Countdown targetDate={item.purge_at}/></span></p><div className="row mid" style={{marginTop:'var(--sp-3)',flexWrap:'wrap'}}><Button size="sm" icon={<RotateCcw size={18}/>} loading={busy} onClick={()=>void restore(item)}>Recover</Button><Button size="sm" variant="danger-text" onClick={()=>setSelected(item)}>Hamesha ke liye hatao</Button></div></Card>)}</div>}
    {toast&&<p role="status" className="t-body-sm">{toast}</p>}
  </main><Dialog isOpen={!!selected} title="Hamesha ke liye hatao?" body="Ye wapas nahi aayega." primaryLabel={busy?'Rukiye…':'Haan, hatao'} primaryVariant="danger-filled" onPrimary={permanentlyDelete} onCancel={()=>setSelected(null)} testId="rd.delete.confirm"/></>;
}
