'use client';
import React from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';
import {CircleHelp,Languages,Bell,Volume2,RotateCcw,MessageCircle,MessageSquare,FileText,Shield,LogOut,Trash2,ChevronRight,Info} from 'lucide-react';
import {AppBar} from '@/components/AppBar';import {Card,SettingsRow} from '@/components/Cards';import {Button} from '@/components/Button';import {TextField} from '@/components/TextField';import {BottomSheet} from '@/components/BottomSheet';import {Dialog} from '@/components/Dialog';import {ToggleRow} from '@/components/Toggle';import {SegmentedControl} from '@/components/SegmentedControl';import {createClient} from '@/lib/supabase/client';import {enablePush} from '@/lib/push';
export default function ProfileView({userId,name,email,tips,language}:{userId:string;name:string;email:string;tips:boolean;language:string}){
 const router=useRouter();const [currentName,setName]=React.useState(name);const [editName,setEditName]=React.useState(false);const [nameDraft,setNameDraft]=React.useState(name);const [busy,setBusy]=React.useState(false);const [toast,setToast]=React.useState('');const [tipsOn,setTipsOn]=React.useState(tips);const [lang,setLang]=React.useState(language);const [sheet,setSheet]=React.useState<'language'|'feedback'|null>(null);const [feedback,setFeedback]=React.useState('');const [notify,setNotify]=React.useState(typeof Notification!=='undefined'&&Notification.permission==='granted');const [sound,setSound]=React.useState(false);const [dialog,setDialog]=React.useState<'logout'|'account'|'data'|null>(null);const [confirmName,setConfirmName]=React.useState('');const [deleteError,setDeleteError]=React.useState('');
 const db=React.useMemo(()=>createClient(),[]);React.useEffect(()=>setSound(localStorage.getItem('token-audio-all')==='true'),[]);
 const saveName=async()=>{if(nameDraft.trim().length<2){setToast('Naam kam se kam 2 akshar ka likhein.');return}setBusy(true);const {error}=await db.from('users').update({name:nameDraft.trim()}).eq('id',userId);setBusy(false);if(error){setToast('Naam save nahi ho paya. Dobara koshish karein.');return}setName(nameDraft.trim());setEditName(false);setToast('Naam badal gaya.')};
 const setTips=async(value:boolean)=>{setTipsOn(value);const {error}=await db.from('users').update({helper_tips_enabled:value}).eq('id',userId);if(error){setTipsOn(!value);setToast('Setting save nahi ho payi. Dobara koshish karein.')}};
 const setLanguage=async(value:string)=>{if(value==='en'){setSheet(null);setToast('English copy abhi available nahi hai.');return}setLang(value);localStorage.setItem('tokenapp-language',value);const {error}=await db.from('users').update({language:value}).eq('id',userId);setSheet(null);if(error)setToast('Language setting save nahi ho payi.')};
 const notifications=async(value:boolean)=>{if(value){try{const result=await enablePush();const {error}=await db.from('push_subscriptions').upsert({user_id:userId,endpoint:result.subscription.endpoint,keys:result.keys},{onConflict:'user_id,endpoint'});if(error)throw error;setNotify(true);setToast('Notification chalu ho gayi.')}catch{setNotify(false);setToast('Notification chalu nahi ho payi. iPhone par Home Screen app kholein.')}}else{const reg=await navigator.serviceWorker?.getRegistration('/sw.js');const sub=await reg?.pushManager.getSubscription();if(sub){await db.from('push_subscriptions').delete().eq('endpoint',sub.endpoint);await sub.unsubscribe()}setNotify(false);setToast('Notification band kar di.')}};
 const deleteAccount=async()=>{setBusy(true);setDeleteError('');const response=await fetch('/api/account/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirmationName:confirmName})});setBusy(false);if(!response.ok){const data=await response.json().catch(()=>({}));setDeleteError(data.error==='name_mismatch'?'Naam match nahi hua.':data.error==='missing_key'?'Account delete service configure nahi hai.':'Account delete nahi ho paya. Dobara koshish karein.');return}await db.auth.signOut();router.replace('/');router.refresh()};
 return <><AppBar title="Profile" isRootTab testId="profile.appbar"/><main className="container page tight" data-testid="profile">
  <Card big testId="profile.card"><h2 className="t-h2">{currentName}</h2><p className="t-body-sm c2">{email}</p><Button variant="tertiary" size="sm" onClick={()=>{setNameDraft(currentName);setEditName(true)}}>Naam badlein</Button></Card>
  <section><h2 className="t-overline c2" style={{marginBottom:'var(--sp-2)'}}>MADAD</h2><Card style={{padding:0}}><SettingsRow icon={<CircleHelp/>} label="Guide (Madad)" onClick={()=>router.push('/app/guide')}/><ToggleRow icon={<Info/>} label="Madad ke tips" checked={tipsOn} onChange={setTips}/></Card></section>
  <section><h2 className="t-overline c2" style={{marginBottom:'var(--sp-2)'}}>SETTINGS</h2><Card style={{padding:0}}><SettingsRow icon={<Languages/>} label="Language" value={lang==='hi'?'Hinglish':'English'} onClick={()=>setSheet('language')}/><SettingsRow icon={<Bell/>} label="Notification" value={notify?'Chalu':'Band'} onClick={()=>void notifications(!notify)}/><ToggleRow icon={<Volume2/>} label="Awaaz" checked={sound} onChange={value=>{setSound(value);localStorage.setItem('token-audio-all',String(value));if(value&&'speechSynthesis'in window)window.speechSynthesis.speak(new SpeechSynthesisUtterance('Awaaz chalu ho gayi'))}}/><SettingsRow icon={<RotateCcw/>} label="Recently Deleted" onClick={()=>router.push('/app/profile/recently-deleted')}/></Card></section>
  <section><h2 className="t-overline c2" style={{marginBottom:'var(--sp-2)'}}>SUPPORT</h2><Card style={{padding:0}}><SettingsRow icon={<MessageCircle/>} label="Madad chahiye?" value="Jaldi add hogi"/><SettingsRow icon={<MessageSquare/>} label="Feedback bhejein" onClick={()=>setSheet('feedback')}/><Link className="profile-row" href="/terms"><FileText/>Terms<ChevronRight/></Link><Link className="profile-row" href="/privacy"><Shield/>Privacy Policy<ChevronRight/></Link></Card></section>
  <section><h2 className="t-overline c2" style={{marginBottom:'var(--sp-2)'}}>ACCOUNT</h2><Card style={{padding:0}}><SettingsRow icon={<LogOut/>} label="Logout" onClick={()=>setDialog('logout')}/><SettingsRow icon={<Trash2/>} label="Account delete karein" onClick={()=>{setConfirmName('');setDialog('account')}}/><SettingsRow icon={<Trash2/>} label="Mera saara data hamesha ke liye hatao" onClick={()=>{setConfirmName('');setDialog('data')}}/></Card></section>
  <p className="t-caption c2" style={{textAlign:'center'}}>Version 1.0.0</p>{toast&&<p role="status" className="t-body-sm">{toast}</p>}
 </main>
 <BottomSheet isOpen={editName} onClose={()=>setEditName(false)} title="Naam badlein" primaryAction={<Button fullWidth loading={busy} onClick={saveName}>Save karein</Button>} secondaryAction={<Button fullWidth variant="tertiary" onClick={()=>setEditName(false)}>Wapas</Button>} testId="profile.name.sheet"><TextField label="Poora naam" value={nameDraft} onChange={e=>setNameDraft(e.target.value.slice(0,40))} maxLength={40}/></BottomSheet>
 <BottomSheet isOpen={sheet==='language'} onClose={()=>setSheet(null)} title="Language" testId="profile.language"><SegmentedControl options={[{value:'hi',label:'Hinglish'},{value:'en',label:'English'}]} value={lang} onChange={setLanguage}/></BottomSheet>
 <BottomSheet isOpen={sheet==='feedback'} onClose={()=>setSheet(null)} title="Feedback bhejein" primaryAction={<Button fullWidth disabled={!feedback.trim()} onClick={async()=>{const {error}=await db.from('feedback').insert({user_id:userId,message:feedback.trim()});if(error){setToast('Feedback bheja nahi ja saka. Dobara koshish karein.');return}setSheet(null);setFeedback('');setToast('Feedback bhej diya.')}}>Bhejein</Button>} secondaryAction={<Button fullWidth variant="tertiary" onClick={()=>setSheet(null)}>Wapas</Button>} testId="profile.feedback"><label className="t-label" htmlFor="feedback-text">Feedback</label><textarea id="feedback-text" value={feedback} onChange={e=>setFeedback(e.target.value.slice(0,2000))} rows={4} className="profile-textarea"/></BottomSheet>
 <Dialog isOpen={dialog==='logout'} title="Logout karein?" body="Aap dobara Google se login kar sakte hain. Aapka data safe rahega." primaryLabel="Logout" primaryVariant="danger-filled" onPrimary={async()=>{setBusy(true);await db.auth.signOut();router.replace('/');router.refresh()}} onCancel={()=>setDialog(null)} testId="profile.logout.confirm"/>
 <Dialog isOpen={dialog==='account'||dialog==='data'} title={dialog==='account'?'Account delete karein?':'Mera saara data hamesha ke liye hatao'} body={<div><p>Ye turant aur hamesha ke liye hatega. Recovery nahi hogi.</p><TextField label="Confirm karne ke liye apna naam likhein" value={confirmName} onChange={e=>setConfirmName(e.target.value)} error={deleteError||undefined}/></div>} primaryLabel={busy?'Rukiye…':dialog==='account'?'Account delete karein':'Hamesha ke liye hatao'} primaryVariant="danger-filled" primaryDisabled={confirmName.trim()!==currentName.trim()} onPrimary={deleteAccount} onCancel={()=>setDialog(null)} testId="profile.delete.confirm"/>
 </>;
}
