import LegalPage from '@/components/LegalPage';
export const metadata = { title: 'Terms of Use' };
const sections = [
['1. Seva kya hai','Token App ek digital queue (token) management tool hai. Isse dukaan, salon, clinic jaise businesses ("Queue Owner") apni queue chala sakte hain, aur graahak ("Customer") QR scan karke token le sakte hain aur apna number live dekh sakte hain.\n\nToken App sirf yeh technology deta hai. Business aur graahak ke beech jo bhi seva, kharid ya samjhauta hota hai, usme Token App shamil nahi hai aur uske liye zimmedar nahi hai.\n\nAbhi Seva muft hai. Future me hum paid features jod sakte hain, lekin aisa hone se pehle aapko soochna di jayegi aur aapki sehmati ke bina koi charge nahi lagega.'],
['2. Kaun istemal kar sakta hai','- Seva ka istemal karne ke liye aapki umar kam se kam 18 saal honi chahiye.\n- 18 saal se kam umar ke log sirf apne mata-pita ya guardian ki dekh-rekh aur anumati se hi token le sakte hain. Seva bachchon ke liye alag se nahi banayi gayi hai.\n- Agar aap kisi business ki taraf se Seva chalate hain, to aap confirm karte hain ki aapko us business ki taraf se aisa karne ka adhikar hai.'],
['3. Account','- Login Google account se hota hai. Aap jo jaankari dete hain wo sahi aur nayi honi chahiye.\n- Aapke account se hone wali har gatividhi ke liye aap zimmedar hain. Apna login surakshit rakhein.\n- Agar aapko lagta hai ki aapka account bina ijazat istemal hua hai, to turant humein batayein (neeche "Sampark" dekhein).'],
['4. Queue Owner ki zimmedariyan','Agar aap queue banate hain, to aap maante hain ki:\n\n- Queue ka naam, business ka naam, token limit, counter ki settings aur average time jaisi cheezein sahi hongi aur aapke business ke hisaab se hongi.\n- Aap graahakon ke tokens ko nishpaksh tareeke se, line ke kram me hi sambhalenge, aur Seva ka istemal kisi ko dhoka dene ya galat jaankari dene ke liye nahi karenge.\n- Customers ka naam aur token ki jaankari sirf queue chalane ke liye istemal karenge, kisi aur maksad (jaise marketing, bechna ya publicly share karna) ke liye nahi.\n- Apni queue ka QR code aur code kisi ko dene ke liye aap khud zimmedar hain.\n- Aap apne business par lagu hone wale kanoon ka paalan karenge.'],
['5. Customer ki zimmedariyan','- Token lene se pehle apna sahi naam likhein. Kisi aur ka naam, jhootha naam, ya kisi aur ki pehchaan ka galat istemal mana hai.\n- Naam ke alawa koi aur private jaankari (phone number, pata, bank details aadi) naam ke box me na likhein.\n- Aapka display name us queue ke owner ko aur line ke doosre logon ko dikh sakta hai (Privacy Policy dekhein). Chahein to apna pehla naam ya chhota naam istemal karein.\n- Token ka number aur intezaar ka samay sirf anumaan (estimate) hota hai. Isliye apni baari se pehle aas-paas hi rahein.'],
['6. Jo karna mana hai','Aap yeh nahi karenge:\n\n- Harassment, dhamki, gaali-galoch, ya doosron ka apmaan. Aise naam likhna jo aapattijanak, gair-kanooni ya doosron ko hurt karne wale hon.\n- Spam, nakli ya bahut saare tokens lena, ya line me kisi ko nuksan pahunchane ki koshish karna.\n- Seva ya uske servers par attack, scraping, bots, reverse-engineering, ya security todne ki koshish karna. Doosre ke account ya queue tak bina ijazat pahunchna.\n- Kisi aur ke queue code ka andaza lagakar ya baar-baar try karke queues ya data tak pahunchne ki koshish karna.\n- Seva ka istemal kisi gair-kanooni kaam ke liye karna.'],
['7. Aapki jaankari aur privacy','Hum aapki jaankari kaise istemal aur surakshit karte hain, yeh hamari Privacy Policy me likha hai. Terms ke saath use bhi padhein.'],
['8. Live updates aur awaaz','Live update aur awaaz network, browser, phone ki settings (jaise battery saver) aur doosre karanon se der se aa sakte hain ya nahi bhi aa sakte hain.'],
['9. Account delete karna','Aap Profile me jaakar apna account delete kar sakte hain. Account delete hone par aap log out ho jaate hain. Yeh action wapas nahi hota.'],
['10. Suspension aur band karna','Agar aap in Terms ka ulanghan karte hain, Seva ya doosre logon ko nuksan pahunchate hain, ya kanoon ke tahat zaroori ho, to hum bina pehle bataye aapka account ya queue rok sakte hain ya hata sakte hain. Aap bhi kabhi bhi Seva ka istemal band kar sakte hain.'],
['11. Hamare adhikar (Intellectual Property)','Token App ka naam, logo, design, code aur content Token App ya uske licensors ka hai. Aapko Seva sirf apne niji ya business ke queue chalane ke liye istemal karne ka seemit adhikar milta hai. Aap ise copy, bech ya badal nahi sakte. Aap jo naam ya queue ki jaankari daalte hain, wo aapki hi rehti hai; Seva chalane ke liye hum use istemal kar sakte hain.'],
['12. Teesri party ki sevayein','Seva chalane ke liye hum teesri party ki sevaon (jaise Google login, database aur hosting, error monitoring) ka istemal karte hain. Unke apne niyam bhi lagu ho sakte hain. Unki wajah se aayi rukawat ke liye hum zimmedar nahi hain.'],
['13. Seva "jaisi hai waisi"','Seva "jaisi hai" aur "jaisi uplabdh hai" ke aadhar par di jaati hai. Hum guarantee nahi dete ki Seva hamesha chalegi, bina galti ke hogi, ya kisi khaas samay par uplabdh hogi. Hum kisi bhi queue me token ke samay, number call hone ki guarantee nahi dete. Hum kisi business ki seva, quality, kimat, ya graahak aur business ke beech ke vivad ki guarantee ya zimmedari nahi lete.'],
['14. Zimmedari ki seema','Kanoon jitni anumati deta hai, us had tak Token App, uske malik, karmchari aur partners kisi bhi seedhe ya anya nuksan (jaise samay ka nuksan, graahak ya aay ka nuksan, ya data ka nuksan) ke liye zimmedar nahi honge, jo Seva ke rukne, der se chalne, galat jaankari dikhane  ho. Jahan kanoon isse zyada zimmedari tay karta ho, wahan sirf utni hi zimmedari lagu hogi. Aapke kanooni adhikar isse kam nahi hote.'],
['15. Aapki taraf se muavza','Agar Terms todne ya Seva ke galat istemal ki wajah se kisi doosre ki shikayat ya nuksan hota hai aur humein uska jawab dena padta hai, to aap utni had tak humein bachane me sehyog karenge, jitna kanoon anumati deta hai.'],
['16. In Terms me badlaav','Hum samay-samay par Terms badal sakte hain. Badlaav is page par naye "Aakhri update" ki taareekh ke saath dikhega. Badlaav ke baad Seva ka istemal jaari rakhna naye Terms ki manzoori mana jaayega.'],
['17. Lagu kanoon aur vivad','Yeh Terms Bharat ke kanoon ke tahat hain. Kisi bhi vivad me Bharat ki sakshm adaalaton ko adhikar hoga. Vivad hone par pehle humse seedha sampark karein, hum use aapsi baat se suljhane ki koshish karenge.'],
['18. Sampark aur shikayat','Sawal, shikayat, ya account se judi kisi bhi madad ke liye humein email karein:\n\nnextmetokensupport@gmail.com\n\nHum aapki shikayat ka jawab jaldi se jaldi dene ki koshish karenge.'],
['19. Aam shartein','Agar in Terms ka koi hissa lagu nahi ho sakta, to baaki hissa lagu rahega. In Terms aur Privacy Policy milkar hamare aur aapke beech poora samjhauta hain. Agar hum kisi adhikar ka istemal turant na karein, to iska matlab yeh nahi ki humne wo adhikar chhod diya.'],
];
export default function Terms() { return <LegalPage title="Terms of Use" showUpdated={false}><p><b>Token App</b><br/>Aakhri update: 4 October 2026</p><p className="t-body-sm">Yeh Terms of Use ("Terms") Token App ki website aur app ("Seva") ke istemal par lagu hote hain. Seva ko Token App ("hum") chalata hai. Seva ka istemal karke aap in Terms aur hamari Privacy Policy se sehmat hote hain. Agar aap sehmat nahi hain, to kripya Seva ka istemal na karein.</p>{sections.map(([title,body])=><section className="legal-section" key={title}><h2 className="t-h3">{title}</h2>{body.split('\n\n').map((p,i)=><p key={i} className="t-body-sm">{p}</p>)}</section>)}</LegalPage>; }
